### ISSUE TITLE
Build dump-package as a seperate binary tool

### ISSUE THREAD

**Issue by thaygiaoth** [holocm/holo-build#16]
Hi all

I want build dump-package as a seperate binary tool for view rpm structure on RHEL/CentOS 7

Please help me step by step how to build it?

Tks

**Comment by majewsky** [comment]
Clone the repo and `make build/dump-package` to produce the binary at that location.
Am 30.07.18, 09:19, thaygiaoth <notifications@github.com> schrieb:
Hi all
I want build dump-package as a seperate binary tool for view rpm structure on RHEL/CentOS 7
Please help me step by step how to build it?
Tks

—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or mute the thread.
{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/holocm/holo-build","title":"holocm/holo-build","subtitle":"GitHub repository","main_image_url":"https://assets-cdn.github.com/images/email/message_cards/header.png","avatar_image_url":"https://assets-cdn.github.com/images/email/message_cards/avatar.png","action":{"name":"Open in GitHub","url":"https://github.com/holocm/holo-build"}},"updates":{"snippets":[{"icon":"DESCRIPTION","message":"Build dump-package as a seperate binary tool (#16)"}],"action":{"name":"View Issue","url":"https://github.com/holocm/holo-build/issues/16"}}}
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/holocm/holo-build/issues/16",
"url": "https://github.com/holocm/holo-build/issues/16",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
},
{
"@type": "MessageCard",
"@context": "http://schema.org/extensions",
"hideOriginalBody": "false",
"originator": "AF6C5A86-E920-430C-9C59-A73278B5EFEB",
"title": "Build dump-package as a seperate binary tool (#16)",
"sections": [
{
"text": "",
"activityTitle": "**thaygiaoth**",
"activityImage": "https://assets-cdn.github.com/images/email/message_cards/avatar.png",
"activitySubtitle": "@thaygiaoth",
"facts": [
{
"name": "Repository: ",
"value": "holocm/holo-build"
},
{
"name": "Issue #: ",
"value": 16
}
]
}
],
"potentialAction": [
{
"name": "Add a comment",
"@type": "ActionCard",
"inputs": [
{
"isMultiLine": true,
"@type": "TextInput",
"id": "IssueComment",
"isRequired": false
}
],
"actions": [
{
"name": "Comment",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"IssueComment\",\n\"repositoryFullName\": \"holocm/holo-build\",\n\"issueId\": 16,\n\"IssueComment\": \"{{IssueComment.value}}\"\n}"
}
]
},
{
"name": "Close issue",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"IssueClose\",\n\"repositoryFullName\": \"holocm/holo-build\",\n\"issueId\": 16\n}"
},
{
"targets": [
{
"os": "default",
"uri": "https://github.com/holocm/holo-build/issues/16"
}
],
"@type": "OpenUri",
"name": "View on GitHub"
},
{
"name": "Unsubscribe",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"MuteNotification\",\n\"threadId\": 362256821\n}"
}
],
"themeColor": "26292E"
}
]

**Comment by thaygiaoth** [comment]
Hi majewsky 

After compiled, I have dump-package binary 
But I using this command
build]# ./dump-package /root/httpd-2.4.6-80.el7.centos.1.x86_64.rpm
It is hang and not output any values

Please help me, tks

**Comment by thaygiaoth** [comment]
It's worked, tks so much!
Solved

**Comment by thaygiaoth** [comment]
closed
