### ISSUE TITLE
Support for SemVer

### ISSUE THREAD

**Issue by yakubin** [holocm/holo-build#23]
Hello,

I wanted to use `holo-build` for packaging my program, but, according to the manpage, the version format is rather strict. E.g. it forbids dashes; this rules out any alpha/beta versions formatted according to SemVer.

What's your view on adding full support for SemVer to `holo-build`?

**Comment by majewsky** [comment]
It's not just our choice. The target package formats also need to support it. (It wouldn't be of much use if we technically allowed "1.0.0-beta.1", but then had to say "sorry, $FORMAT does not support dashes in the version"). I went with the restriction on numerical versions since these are always safe. (Personally, when I need a beta version like "1.2.0-beta.1", I do "1.1.91" instead.)

Additional version syntax could be added, but that would require checking whether dpkg/RPM/pacman support these version formats. If you (or someone else) wants to make a PR, some notes:

- For dpkg, the Debian Policy Manual defines which version strings are acceptable. For RPM and pacman, I'm not aware of actual specifications that define grammars for version strings. (RPM is defined in the LSB, but that spec is frankly a joke.) So in these cases, finding out which versions are acceptable might come down to actually reading the source code of the package manager.

- If a particular syntax is supported only by some package formats, it can still be added to holo-build. But for those package formats that don't support it, the respective generator would either have to rewrite the version string into something that is accepted, or deny that format. (There are already some cases where generally valid package formats are rejected by a particular generator, e.g. [here](https://github.com/holocm/libpackagebuild/blob/e8910bea736e4333fc6d6455b49732b60d92ebc1/debian/generator.go#L76-L86) for the dpkg generator.)

**Comment by yakubin** [comment]
The way I see it, it would be ideal if `holo-build` could parse SemVer and accommodate different distro conventions as appropriate. E.g. versions of DEB packages cannot contain dashes. The common solution to this problem (employed e.g. by `cargo-deb`) is to replace the dash with a tilde; so "1.0.0-beta.1" becomes "1.0.0~beta.1".

I'm not sure about the others. As far as I remember, RPM has a convention that would never prompt me to think that it's about beta releases at all. I may dedicate some time on a weekend to gather information on what kind of restrictions apply in different distros regarding Semantic Versioning and post it here. Then the "SemVer -> distro version" conversion should be easier to figure out. Unless you don't want to go this way of course.

**Comment by majewsky** [comment]
> The way I see it, it would be ideal if holo-build could parse SemVer and accommodate different distro conventions as appropriate.

That is what I meant by "the respective generator [could] rewrite the version string into something that is accepted".

> I may dedicate some time on a weekend to gather information on what kind of restrictions apply in different distros regarding Semantic Versioning and post it here.

That would be much appreciated. I don't have much time to spend on this project ATM, it's very much in maintenance mode from my perspective since it does everything I need it to do. If you (or someone else) sends a PR, I'll be happy to review it and make a new release once it's merged.

**Comment by yakubin** [comment]
I created a pull request (#24).

It adds support just for basic "alphas" and "betas"; not for the full SemVer. I did that because when I discovered that SemVer allows things like "1.0.0-alpha.beta", I concluded that it's unnecessarily complicated and I can't think of a situation when I would want to use such a construct. This way I think the code will be a bit simpler and less error-prone.

**Comment by yakubin** [comment]
Closing, as #24 is merged. Thanks.
